config/routes.rb
Rails.application.routes.draw do
  # get 'students/index'
  resources :students
  resources :teachers
  resources :exams

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
    def new #untuk menampilkan form data baru
        @exam = Exam.new
      end    
      def create #untuk memperoses data baru yang dimasukkan di form new
        exam = Exam.new (resources_params)
        exam.save 
        redirect_to exams_path
        flash[:notice] = 'Exam has been created'
      end   
      def edit #menampilkan data yang sudah disimpan
        @exam = Exam.find(params[:id])
      end  
      def update #melakukan proses ketika user mengedit data
      @exam = Exam.find(params[:id])
      @exam.update(resources_params)
      flash[:notice] = 'Exam has been update'
      redirect_to exam_path(@exam)
      end    
      def destroy #untuk menghapus data
        @exam = Exam.find(params[:id])
        @exam.destroy
        flash[:notice] = 'Exam has been destroy'
        redirect_to exams_path(@exam)
      end  
      def index #menampilkan seluruh data yang ada di database
        @exams = Exam.all
      end    
      def show #menampilkan  sebuah data sectemplateara detail
        id = params[:id]
        @exam = Exam.find(id)
        # render plain: id
        # render plain: @book.title 
       end
      private    
      def resources_params
        params.required(:exam).permit(:title, :mapel, :duration, :nilai, :keaktifan, :level, :student_id)
      end  
    end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new #untuk menampilkan form data baru
    @student = Student.new
  end    
  def create #untuk memperoses data baru yang dimasukkan di form new
    student = Student.new (resources_params)
    student.save 
    redirect_to students_path
    flash[:notice] = 'Student has been created'
  end   
  def edit #menampilkan data yang sudah disimpan
    @student = Student.find(params[:id])
  end  
  def update #melakukan proses ketika user mengedit data
  @student = Student.find(params[:id])
  @student.update(resources_params)
  flash[:notice] = 'Student has been update'
  redirect_to student_path(@student)
  end    
  def destroy #untuk menghapus data
    @student = Student.find(params[:id])
    @student.destroy
    flash[:notice] = 'Student has been destroy'
    redirect_to students_path(@student)
  end  
  def index #menampilkan seluruh data yang ada di database
    @students = Student.all
  end    
  def show #menampilkan  sebuah data sectemplateara detail
    id = params[:id]
    @student = Student.find(id)
    # render plain: id
    # render plain: @book.title 
   end
  private    
  def resources_params
    params.required(:student).permit(:name, :username, :age, :rombel, :address, :city, :nik)
  end  
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
def new #untuk menampilkan form data baru
    @teacher = Teacher.new
  end    
  def create #untuk memperoses data baru yang dimasukkan di form new
    teacher = Teacher.new (resources_params)
    teacher.save 
    redirect_to teachers_path
    flash[:notice] = 'teacher has been created'
  end   
  def edit #menampilkan data yang sudah disimpan
    @teacher = Teacher.find(params[:id])
  end  
  def update #melakukan proses ketika user mengedit data
  @teacher = Teacher.find(params[:id])
  @teacher.update(resources_params)
  flash[:notice] = 'Teacher has been update'
  redirect_to teacher_path(@teacher)
  end    
  def destroy #untuk menghapus data
    @teacher = Teacher.find(params[:id])
    @teacher.destroy
    flash[:notice] = 'Teacher has been destroy'
    redirect_to teachers_path(@teacher)
  end  
  def index #menampilkan seluruh data yang ada di database
    @teachers = Teacher.all
  end    
  def show #menampilkan  sebuah data sectemplateara detail
    id = params[:id]
    @teacher = Teacher.find(id)
    # render plain: id
    # render plain: @book.title 
   end
  private    
  def resources_params
    params.required(:teacher).permit(:NIK, :name, :age, :kelas, :mapel)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/exams/edit.html.erb
<%= form_for(@exam) do |f| %>

    <%= f.label :title %> </br> 
    <%= f.text_field :title %> </br> 

    <%= f.label :mapel %> </br> 
    <%= f.text_field :mapel %> </br> 

    <%= f.label :duration %> </br> 
    <%= f.text_field :duration %> </br>

    <%= f.label :nilai %> </br> 
    <%= f.text_field :nilai %> </br>

    <%= f.label :keaktifan %> </br> 
    <%= f.text_field :keaktifan %> </br>

     <%= f.label :level %> </br> 
    <%= f.text_field :level %> </br>

     <%= f.label :student_id %> </br> 
    <%= f.text_field :student_id %> </br>

    <%= f.submit "Save" %> 
    <%= link_to 'Back', exams_path %> 

    

<% end %>

app/views/exams/index.html.erb
<h1>Exams#index</h1>
<p>Find me in app/views/exams/index.html.erb</p>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<% if flash[:notice].present? %>

<%= flash[:notice] %>

<% end %> </br>

<table class="table table-striped">

    <thead class="thead-dark">

    <tr>

        <th>Title</th>

        <th>Mapel</th>

        <th>Duration</th>

        <th>Nilai</th>

        <th>Keaktifan</th>

        <th>Level</th>

        <th>Student_id<th>

    </tr>

    </thead>

    <tbody>

    <% @exams.each do |exam| %>

    <tr>

        <td><%= exam.title %></td>

        <td><%= exam.mapel %></td>

        <td><%= exam.duration %></td>

        <td><%= exam.nilai %></td>

        <td><%= exam.keaktifan %></td>

        <td><%= exam.level %></td>

        <td><%= exam.student_id %></td>

        <td><%= link_to 'Detail', exam_path(exam) %> | <%= link_to 'Edit', edit_exam_path(exam) %> | <%= link_to 'Delete', exam_path(exam) , method: :delete, data: {confirm: 'Apakah anda yakin?'} %></td>

        

    </tr>

    <% end %>

    </tbody>

</table> 

<%= link_to 'New Exam', new_exam_path() %>

app/views/exams/new.html.erb
<%= form_for(@exam) do |s| %>

    <%= s.label :title %> </br> 
    <%= s.text_field :title %> </br> 

    <%= s.label :mapel %> </br> 
    <%= s.text_field :mapel %> </br> 

    <%= s.label :duration %> </br> 
    <%= s.text_field :duration %> </br>

    <%= s.label :nilai %> </br> 
    <%= s.text_field :nilai %> </br>

    <%= s.label :keaktifan %> </br> 
    <%= s.text_field :keaktifan %> </br>

     <%= s.label :level %> </br> 
    <%= s.text_field :level %> </br>

     <%= s.label :student_id %> </br> 
    <%= s.text_field :student_id %> </br>

    <%= s.submit "Save" %> 
    <%= link_to 'Back', exams_path %> 

    

<% end %>

app/views/exams/show.html.erb
<% if flash[:notice].present? %>

<%= flash[:notice] %>

<% end %> </br>

Name : <%= @exam.title %> </br>

Username : <%= @exam.mapel %> </br>

Age : <%= @exam.duration %> </br>

Rombel : <%= @exam.nilai %> </br>

Address : <%= @exam.keaktifan %> </br>

City : <%= @exam.level %> </br>

NIK : <%= @exam.student_id %> </br>

 <%= link_to 'Back', exams_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<%= form_for(@student) do |f| %>

    <%= f.label :name %> </br> 

    <%= f.text_field :name %> </br> 

    <%= f.label :username %> </br> 

    <%= f.text_field :username %> </br> 

    <%= f.label :age %> </br> 

    <%= f.text_field :age %> </br>

    <%= f.label :rombel %> </br> 

    <%= f.text_field :rombel %> </br>

    <%= f.label :address %> </br> 

    <%= f.text_field :address %> </br>

     <%= f.label :city %> </br> 

    <%= f.text_field :city %> </br>

     <%= f.label :NIK %> </br> 

    <%= f.text_field :NIK %> </br>

    <%= f.submit "Save" %> 

    <%= link_to 'Back', students_path %> 

    

<% end %>

app/views/students/index.html.erb
<h1>Students#index</h1>
<p>Find me in app/views/students/index.html.erb</p>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<% if flash[:notice].present? %>

<%= flash[:notice] %>

<% end %> </br>

<table class="table table-striped">

    <thead class="thead-dark">

    <tr>

        <th>Name</th>

        <th>Username</th>

        <th>Age</th>

        <th>Rombel</th>

        <th>Address</th>

        <th>City</th>

        <th>NIK<th>

    </tr>

    </thead>

    <tbody>

    <% @students.each do |student| %>

    <tr>

        <td><%= student.name %></td>

        <td><%= student.username %></td>

        <td><%= student.age %></td>

        <td><%= student.rombel %></td>

        <td><%= student.address %></td>

        <td><%= student.city %></td>

        <td><%= student.NIK %></td>

        <td><%= link_to 'Detail', student_path(student) %> | <%= link_to 'Edit', edit_student_path(student) %> | <%= link_to 'Delete', student_path(student) , method: :delete, data: {confirm: 'Apakah anda yakin?'} %></td>

        

    </tr>

    <% end %>

    </tbody>

</table> 

<%= link_to 'New Student', new_student_path() %>

app/views/students/new.html.erb
<%= form_for(@student) do |s| %>

    <%= s.label :name %> </br> 

    <%= s.text_field :name %> </br> 

    <%= s.label :username %> </br> 

    <%= s.text_field :username %> </br> 

    <%= s.label :age %> </br> 

    <%= s.text_field :age %> </br>

    <%= s.label :rombel %> </br> 

    <%= s.text_field :rombel %> </br>

    <%= s.label :address %> </br> 

    <%= s.text_field :address %> </br>

    <%= s.label :city %> </br> 

    <%= s.text_field :city %> </br>

    <%= s.label :NIK %> </br> 

    <%= s.text_field :NIK %> </br>

    <%= s.submit "Save" %> 

    <%= link_to 'Back', students_path %> 

    

<% end %>

app/views/students/show.html.erb
<% if flash[:notice].present? %>

<%= flash[:notice] %>

<% end %> </br>

Name : <%= @student.name %> </br>

Username : <%= @student.username %> </br>

Age : <%= @student.age %> </br>

Rombel : <%= @student.rombel %> </br>

Address : <%= @student.address %> </br>

City : <%= @student.city %> </br>

NIK : <%= @student.NIK %> </br>

 <%= link_to 'Back', students_path %> 

app/views/teachers/edit.html.erb
<%= form_for(@teacher) do |s| %>

    <%= s.label :NIK %> </br> 
    <%= s.text_field :NIK %> </br> 

    <%= s.label :name %> </br> 
    <%= s.text_field :name %> </br> 

    <%= s.label :age %> </br> 
    <%= s.text_field :age %> </br>

    <%= s.label :kelas %> </br> 
    <%= s.text_field :kelas %> </br>

    <%= s.label :mapel %> </br> 
    <%= s.text_field :mapel %> </br>

    <%= s.submit "Save" %> 

    <%= link_to 'Back', teachers_path %> 

    

<% end %>

app/views/teachers/index.html.erb
<h1>Teacher#index</h1>
<p>Find me in app/views/teacher/index.html.erb</p>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<% if flash[:notice].present? %>

<%= flash[:notice] %>

<% end %> </br>

<table class="table table-striped">

    <thead class="thead-dark">

    <tr>

        <th>NIK</th>

        <th>Name</th>

        <th>Age</th>

        <th>Kelas</th>

        <th>Mapel</th>


    </tr>

    </thead>

    <tbody>

    <% @teachers.each do |teacher| %>

    <tr>

        <td><%= teacher.NIK %></td>

        <td><%= teacher.name %></td>

        <td><%= teacher.age %></td>

        <td><%= teacher.kelas %></td>

        <td><%= teacher.mapel %></td>

        <td><%= link_to 'Detail', teacher_path(teacher) %> | <%= link_to 'Edit', edit_teacher_path(teacher) %> | <%= link_to 'Delete', teacher_path(teacher) , method: :delete, data: {confirm: 'Apakah anda yakin?'} %></td>

        

    </tr>

    <% end %>

    </tbody>

</table> 

<%= link_to 'New Teacher', new_teacher_path() %>

app/views/teachers/new.html.erb
<%= form_for(@teacher) do |s| %>

    <%= s.label :NIK %> </br> 
    <%= s.text_field :NIK %> </br> 

    <%= s.label :name %> </br> 
    <%= s.text_field :name %> </br> 

    <%= s.label :age %> </br> 
    <%= s.text_field :age %> </br>

    <%= s.label :kelas %> </br> 
    <%= s.text_field :kelas %> </br>

    <%= s.label :mapel %> </br> 
    <%= s.text_field :mapel %> </br>

    <%= s.submit "Save" %> 
    <%= link_to 'Back', teachers_path %> 

    

<% end %>

app/views/teachers/show.html.erb
<% if flash[:notice].present? %>

<%= flash[:notice] %>

<% end %> </br>

Name : <%= @teacher.NIK %> </br>

Username : <%= @teacher.name %> </br>

Age : <%= @teacher.age %> </br>

Rombel : <%= @teacher.kelas %> </br>

Address : <%= @teacher.mapel %> </br>

 <%= link_to 'Back', teachers_path %> 